### ISSUE TITLE
Use headers for authentication rather than URL parameters

### ISSUE THREAD

**Issue by edmorley** [AutomatedTester/Bugsy#29]
Bugzilla supports using custom HTTP headers for the various authentication fields, instead of passing them as parameters in the request URL.

This prevents them from accidentally being included in logs.

The header key names can be found here:
https://github.com/mozilla/webtools-bmo-bugzilla/blob/f70d4ce7e0a94379bb901559109650874946c84b/Bugzilla/WebService/Constants.pm#L305-L310
```perl
use constant API_AUTH_HEADERS => {
    X_BUGZILLA_LOGIN    => 'Bugzilla_login',
    X_BUGZILLA_PASSWORD => 'Bugzilla_password',
    X_BUGZILLA_API_KEY  => 'Bugzilla_api_key',
    X_BUGZILLA_TOKEN    => 'Bugzilla_token',
};
```

**Comment by markrcote** [comment]
I'm taking a look at this right now. FYI the headers are actually

X-Bugzilla-Login
X-Bugzilla-Password
X-Bugzilla-API-Key
X-Bugzilla-Token
