### ISSUE TITLE
Let `bug` set/get keywords

### ISSUE THREAD

**Issue by KWierso** [AutomatedTester/Bugsy#31]
I need to be able to set keywords on bug creation, and it'd be nice to be able up update them (and fetch them) after creation. The REST API differs for creation vs update in regards to how they get specified.

**Comment by AutomatedTester** [comment]
Getting keywords added in c73c518

**Comment by AutomatedTester** [comment]
setting keywords is on hold until a BMO [Bug]( https://bugzilla.mozilla.org/show_bug.cgi?id=1236652) is fixed
