### ISSUE TITLE
Let `bug` set/get dependencies

### ISSUE THREAD

**Issue by KWierso** [AutomatedTester/Bugsy#32]
I need to be able to set both the 'dependson' and 'blocks' values on bug creation, but that doesn't seem possible at the moment.

**Comment by AutomatedTester** [comment]
Ability to get Blockers and Dependencies on a bug 

124721663312ddad4dfa5479f16dd51760d1b61f

**Comment by AutomatedTester** [comment]
setting blockers/deps is on hold until a BMO [Bug]( https://bugzilla.mozilla.org/show_bug.cgi?id=1236652) is fixed
