### ISSUE TITLE
Let `bug` set/get a bug's Cc list

### ISSUE THREAD

**Issue by KWierso** [AutomatedTester/Bugsy#33]
I want to be able to set the Cc list on bug creation.

**Comment by AutomatedTester** [comment]
Getting a cc list added in 6975449cee34c686d8b2058b5cae3cde1b8a8

**Comment by AutomatedTester** [comment]
setting cc is on hold until a BMO [Bug]( https://bugzilla.mozilla.org/show_bug.cgi?id=1236652) is fixed
