### ISSUE TITLE
Can't log into bugzilla 5.0 dev server on landfill

### ISSUE THREAD

**Issue by Standard8** [AutomatedTester/Bugsy#43]
I'm practising using Bugsy against the landfill 5.0 server at https://landfill.bugzilla.org/bugzilla-5.0-branch/

When I try to log in with an API key, I get:

```
<Response [200]>
{u'result': False}
Traceback (most recent call last):
  File "bin/create_release.py", line 46, in <module>
    main()
  File "bin/create_release.py", line 42, in main
    releaseStandalone(useDev=True)
  File "bin/create_release.py", line 19, in releaseStandalone
    bugzilla = bugsy.Bugsy(username=USERNAME, api_key=DEV_APIKEY, bugzilla_url=bugzillaUrl)
  File "/Users/mark/loop/loop/built/.venv/lib/python2.7/site-packages/bugsy/bugsy.py", line 72, in __init__
    raise LoginException(result['message'])
KeyError: 'message'
```

The first two lines are debug added by me. Trying to use this on production gives the result as True and everything is OK.

**Comment by AutomatedTester** [comment]
When I try log in with a username and password I get the following

```
>>> bz = bugsy.Bugsy(username="<username>", password="<password>", bugzilla_url="https://landfill.bugzilla.org/bugzilla-5.0-branch/rest")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bugsy/bugsy.py", line 80, in __init__
    'X-Bugzilla-Password': password
  File "bugsy/bugsy.py", line 191, in request
    return self._handle_errors(self.session.request(method, url, **kwargs))
  File "bugsy/bugsy.py", line 205, in _handle_errors
    raise BugsyException(result["message"], result.get("code"))
bugsy.errors.BugsyException: Message: The function requires a login argument, and that argument was not set. Code: 50
```

**Comment by AutomatedTester** [comment]
@dklawren can you advise what might be wrong with this setup?

**Comment by dklawren** [comment]
landfill's 5.0 and the code we run on BMO production are definitely different code bases and give no guarantee that the same calls will work the same way. BMO is based on 4.2 with a lot of backported features and other customizations. 

You are better off testing against our internal test server instead:
https://bugzilla-dev.allizom.org

dkl

**Comment by Standard8** [comment]
Based on the previous comment, it looks like its better to run against the dev test server, so I think I'll close this.
